on:
    push:
    pull_request:
      branches: main
jobs:
    test:
        name: Simple Test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
            statuses: write
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Create template from API Platform
              run: git clone https://github.com/api-platform/api-platform api-template
            - name: Create an existing project
              run: |
                    git clone https://github.com/api-platform/api-platform project/
                    cd project/
                    pwd
                    git reset --hard da8b1bac32b13abeb4a3c8b32a6449f0486f904c 

            - name: Run Script
              run: | 
                cd ..
                pwd
                ls
                exit 0
                sh template-sync.sh api-template
            